-- Create packages table
create table if not exists packages (
  id bigint generated by default as identity primary key,
  landing_page_id uuid references landing_pages(id) on delete cascade not null,
  name text not null,
  price numeric not null,
  subtitle text not null,
  benefits jsonb not null default '[]'::jsonb,
  restrictions jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies (copying from services pattern usually)
alter table packages enable row level security;

create policy "Enable read access for all users"
on packages for select
using (true);

create policy "Enable insert for authenticated users only"
on packages for insert
with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
on packages for update
using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
on packages for delete
using (auth.role() = 'authenticated');
